### ISSUE TITLE
Read Bruker Tims data MSnbase error

### ISSUE THREAD

**Issue by yguitton** [lgatto/MSnbase#590] opened 2023-03-14 16:13 UTC
Hi @lgatto, Hi @jorainer 
I've just received mzXML and mzML data converted from Bruker Tims Tof Pro .d files and the error is

` mem <- readMSData(filemzml, mode = "inMemory")
Error: Can not open file C:\Users\ygu\Documents\blank autoMSMS_3_1_2558.mzML! Original error was: Error in pwizModule$open(filename): [MSDataFile::readFile()] Unsupported file format.`

I found in [old post](https://support.bioconductor.org/p/119503/) that the issue can be linked to old version of mzR ou MSnbase but think that I'm up to date with packages 

Maybe not doing the right things, any help appreciated.
Best Yann

My session info
'[1] xcms_3.20.0         MSnbase_2.24.2      ProtGenerics_1.30.0 S4Vectors_0.36.1   
[5] mzR_2.32.0          Rcpp_1.0.9          Biobase_2.58.0      BiocGenerics_0.44.0
[9] BiocParallel_1.32.5'

**Comment by jorainer** [comment] 2023-03-15 06:52
Hi Yann! Your error comes indeed from `mzR`, but you have the current stable `mzR` version - and AFAIK we did not add/change anything in the current devel version (which would be 2.33.0). I guess the problem is the proteowizard version within `mzR` - because the `[MSDataFile::readFile()]` looks like a error message from the proteowizard C++ code.

Two options: 

- a) would it be possible for you to share that failing file (or some other converted file that fails with the same error message)? I could dig a bit into it to see what exactly causes the error - and maybe we (or better said Steffen) would need to update the proteowizard libraries within `mzR`.
- b) I've been updating `xcms` et al to use `Spectra`/`MsExperiment` instead of `MSnbase`. This means that you could import data directly from the Bruker .d files using the [MsBackendTimsTof](https://github.com/RforMassSpectrometry/MsBackendTimsTof). This is however still all work in progress... (all my updates to `xcms` are currently a [PR](https://github.com/sneumann/xcms/pull/666), but the plans are to get this into the next `xcms` release for Bioconductor 3.17 in ~ end of April 2023) but it would also be good if somebody could test it :)

**Comment by jsaintvanne** [comment] 2023-03-17 07:32
Hi @lgatto,
I work with @yguitton and I would try to use your spectra branch of xcms to try it and test it on a file but don't know how to really use it.... I'm trying to `devtools::install_github("https://github.com/sneumann/xcms.git", ref = "spectra")
` but finish with an error. 
Should I clone the repo and then use the branch ? In this case i'm not sure to know how to be sure to use spectra branch and not the main default one ?
Can you help me a little describing me maybe the function to use (if it is just a function) because in your PR you changed a loooooot of files and don't really know what to use to test on Bruckers .d files
Thanks for your help !

**Comment by jorainer** [comment] 2023-03-20 12:06
Hi @jsaintvanne ,

to install the upcoming `xcms` version (it's not yet merged - and after some discussion Steffen and I decided to wait for the next BioC release) you will also need some other (updated) packages. I suggest to **not** do this in a production system, but on a development setup.

```r
devtools::install_github("RforMassSpectrometry/MsCoreUtils")
devtools::install_github("RforMassSpectrometry/Spectra")
devtools::install_github("RforMassSpectrometry/MsExperiment")
devtools::install_github("sneumann/xcms", ref = "spectra")
```

and you will also need the backend that supports the TimsTOF files: [MsBackendTimsTof](https://github.com/RforMassSpectrometry/MsBackendTimsTof); ideally also check that page for additional requirements (needs some libraries from the manufacturer to read the data).

```r
devtools::install_github("RforMassSpectrometry/MsBackendTimsTof")
```

I suggest to test it by reading a single file (assuming parameter `fl` is the path/filename of one *.d* file you have).

```r
library(xcms)
library(MsExperiment)
library(MsBackendTimsTof)

mse <- readMsExperiment(fl, source = MsBackendTimsTof())
```

Next we load all data into memory (that's not ideal, but there is still some required functionality missing in the current `MsBackendTimsTof`). This should in future no longer be needed!

```r
mse@spectra <- setBackend(mse@spectra, MsBackendMemory())
```

you could then run `xcms` preprocessing on that data, the same way you would do it if you used `MSnbase` for data import.

```r
xmse <- findChromPeaks(mse, param = CentWaveParam())
```

There is a lot of things we still need improve in the `MsBackendTimsTof` backend/package ... 


Let me know how that works or if you have any problems.

**Comment by jsaintvanne** [comment] 2023-03-20 12:23
Hi @jorainer 
Thanks a lot for all these clear explanations !

My side, I tried with one file in R directly with the `MsBackendTimsTof ` package (I think if remember well) with this function :
``` sps <- Spectra(my_path_folder, source = MsBackendTimsTof()) ```
Then I used the `write_ms_data_mzR` function to make a `mzML` file and to finish I `readMSData` it !
It looks that works but I have at the final function 2 errors but a result also... Don't know why yet ! 
And now, I will try to test it in Galaxy from the mzML file to see it if it works like this and if we can use it in Galaxy like the other files.

Keep you inform and thanks again !

**Comment by jsaintvanne** [comment] 2023-03-21 10:42
Hi @jorainer 

Have this error when use `setBackEnd` and the same when use `write_ms_data_mzR`..

```
Error in (function (cond) :
erreur d'ï¿½valuation de l'argument 'x' lors de la sï¿½lection d'une mï¿½thode pour la fonction 'as.data.frame' : Default conversion method must be selected BEFORE opening any TimsDataHandles - or it must be passed explicitly to the constructor
```

Possible to help me ? Should it be a package with not the good version ?

**Closed** 2023-05-12 10:09 UTC
